services:
  postgis:
    image: postgis/postgis:16-3.5
    container_name: gis_postgis
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - gis-monitor-network

  pgadmin:
    image: dpage/pgadmin4:9.16
    container_name: gis-monitor-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgis:
        condition: service_healthy
    networks:
      - gis-monitor-network
volumes:
  postgis_data:
    name: gis-monitor-postgis-data
  pgadmin_data:
    name: gis-monitor-pgadmin-data

networks:
  gis-monitor-network:
    name: gis-monitor-network